preferredLocale = "en" ### Preferred locale ###
logLevel = "INFO" ### Log level (OFF, FATAL, ERROR, WARN, INFO, DEBUG, TRACE, ALL) ###
storeCredentials = true # Whether to store reusable credentials on disk (not a plain password)
credentialsFile = "creds.json" # Credentials file (JSON)

### Server ###
[server]
port = 8080 # Selects what port to listen for HTTP requests on
albumEndpoint = "/albumPlayCount" # Endpoint at which the user can send HTTP GET requests to the API for album info
artistEndpoint = "/artistInfo" # Endpoint at which the user can send HTTP GET requests to the API for artist info
artistAboutEndpoint = "/artistAbout" # Endpoint at which the user can send HTTP GET requests to the API for an artist's about page
artistInsightsEndpoint = "/artistInsights" # Endpoint at which the user can send HTTP GET requests to the API for an artist's insights
enableHttps = false # If true, enables HTTPS support
httpsKs = "" # Location to keystore with HTTPS certificate and key
httpsKsPass = "" # Password to HTTPS keystore file (if applicable)